package com.scjppreparation.basics.multithreading;

public class ThreadNames {

	
	//Getting and setting the names of the thread
	
	//every thread in java has some name. i tmay be rpovided by the programmer or default name generated byJVM
	
	//we can get and set the name of the threads by using the following methods
	
	//public final void setName(String name)
	
	//publci final string getName()
	
	
	//we can get the current executing thread reference by using the following method of thread class
	
	//public static thread currentThread()
	public static void main(String[] args) {
		
		System.out.println(Thread.currentThread().getName());
		
		System.out.println(Thread.currentThread());
		
		Thread.currentThread().setName("Amma");
		
		System.out.println(Thread.currentThread().getName());
		
		
		
		
	}
}
